name: Deploy Documentation

on:
  push:
    branches:
      - maister
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      # Step 3: Install pnpm and project dependencies
      - name: Install dependencies
        run: |
          corepack enable pnpm
          pnpm install

      # Step 4: Build the documentation (docs:build)
      - name: Build documentation
        run: pnpm run docs:build

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vitepress/dist
